
import '@angular/compiler';
import { bootstrapApplication } from '@angular/platform-browser';
import { provideHttpClient } from '@angular/common/http';
import { provideZonelessChangeDetection } from '@angular/core';

import { AppComponent } from './src/app.component';
import { APP_CONFIG, AppConfig } from './src/app.config';

/**
 * Asynchronously bootstraps the Angular application.
 * It first fetches the runtime configuration and then uses it to provide
 * environment-specific variables to the application via dependency injection.
 * This approach is robust and prevents race conditions that lead to a blank screen.
 */
async function bootstrap() {
  try {
    // Fetch the configuration file generated by the build script.
    const response = await fetch('./src/runtime-config.json');
    if (!response.ok) {
      throw new Error(`Could not load runtime configuration. Status: ${response.status}`);
    }
    const config: AppConfig = await response.json();

    // Now, bootstrap the Angular application with the fetched configuration.
    bootstrapApplication(AppComponent, {
      providers: [
        provideZonelessChangeDetection(),
        provideHttpClient(),
        // Provide the configuration object under the APP_CONFIG injection token.
        { provide: APP_CONFIG, useValue: config }
      ]
    });
  } catch (error) {
    console.error('Failed to bootstrap the application:', error);
    // Display a user-friendly error message directly in the body if bootstrap fails.
    const rootElement = document.querySelector('app-root');
    if (rootElement) {
       rootElement.innerHTML = `
        <div style="padding: 2rem; text-align: center; font-family: sans-serif; color: #ef4444;">
          <h2>Application failed to start</h2>
          <p>Could not load necessary configuration. Please ensure the application is built and deployed correctly.</p>
          <p style="font-size: 0.8rem; color: #999;">Check the browser console for more details.</p>
        </div>
      `;
    }
  }
}

// Start the bootstrap process.
bootstrap();

// AI Studio always uses an `index.tsx` file for all project types.
