// This file is a placeholder.
// In a deployment environment (like on Render), this file will be dynamically
// generated by a build script with the actual environment variables.
// This allows the frontend application to access configuration securely.
window.runtimeConfig = {
  API_KEY: 'YOUR_GEMINI_API_KEY_PLACEHOLDER',
  AURA_USERNAME: 'aura',
  AURA_PASSWORD: 'password',
  MONGO_URI: '',
  AURA_BACKEND_URL: ''
};
